@@grammar::Able
@@eol_comments :: /#([^\n]*?)$/

start = 'able' ':' '1' @:implicit_list $ ;

float = /[+-]?\d+\.\d*/ ;

decimal_integer = /[+-]?\d+/ ;

number = float | decimal_integer;

double_quoted_string = '"' @:/[^"]+/ '"' ;

single_quoted_string = "'" @:/[^']+/ "'" ;

string = double_quoted_string | single_quoted_string ;

pair = @:/[\w]+/ ':' @:value ;

value = number | string | pair | list ;

list = '[' @:{ value }* ']' ;

implicit_list = { value }* ;
